last_update = 1683127370864
api_url = "https://api.playit.cloud/agent"
ping_target_addresses = ["23.133.216.1:5530", "ping.ply.gg"]
control_address = "control.playit.gg"
refresh_from_api = true
api_refresh_rate = 5000
ping_interval = 5000
secret_key = "df39a19b3ea525a897387bcadaac39de09fa788b1ae86f357e86e7fa18506ced"

[[mappings]]
name = "client"
proto = "both"
tunnel_ip = "147.185.221.229"
tunnel_from_port = 35829

[[mappings]]
name = "server"
proto = "both"
tunnel_ip = "147.185.221.229"
tunnel_from_port = 35821
